### ISSUE TITLE
ec2 cloud-init: user-data script not being executed

### ISSUE THREAD

**Issue by FrankReh** [clearlinux/micro-config-drive#38]
I'm using an AWS AMI, ami-032138b8a0ee244c9 (N. Virginia), which is a stock Clear Linux OS image built in June this year. And I'm using terraform to be able to script the creation of such EC2 instances.

At instance creation, it is not running the user data it is provisioned with. The aws console can display the user data correctly so EC2 seems to think the script provided is legitimate. Once logged into the instance via ssh, the file /var/lib/cloud/aws-user-data contains both the #cloud-config lines and the #!/bin/bash user data script lines. So the data comprising the script has made it into the image.

But there is no /var/lib/cloud/instances directory and no /var/log/cloud-init-output.log.

I'm using terraform to create the instance but this doesn't seem like a terraform issue because the user data I specified made it into instance.

It seems like the step that should pull the lines out of the before mentioned was-user-data file is not pulling those lines out.

The /var/lib/cloud/uaw-user-data file looks like this:
```
#cloud-config
users:
  - name: clear
    groups: wheelnopw
    ssh-authorized-keys:
      - ssh-rsa AAAA..snip..prFt EC2KeyPairName
#!/bin/bash

echo Hello World > /tmp/hello.txt

```
